package com.gmc.entity;

// Generated 2015-4-28 0:21:27 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article")
public class Article implements java.io.Serializable {

	private int articleId;
	private String articleTitle;
	private String articleContent;

	public Article() {
	}

	public Article(int articleId) {
		this.articleId = articleId;
	}

	public Article(int articleId, String articleTitle, String articleContent) {
		this.articleId = articleId;
		this.articleTitle = articleTitle;
		this.articleContent = articleContent;
	}

	@Id
	@Column(name = "article_id", unique = true, nullable = false)
	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	@Column(name = "article_title", length = 45)
	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	@Column(name = "article_content", length = 45)
	public String getArticleContent() {
		return this.articleContent;
	}

	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

}
